### ISSUE TITLE
Querying very slow on large model (1,44gb)

### ISSUE THREAD

**Issue by barthr** [sajari/word2vec#7]
Thanks for this library it has helped me a lot in intergrating `word2vec` embeddings in my go program. Currently I have a very large model trained with `gensim python` and saved to file as word2vec binary. Querying works perfect but it is really slow. 1 query costs around 1 second to get a match using the `CosN` method. Any ideas how to speed this up? Is it because my model is to big or is there something else I could do to speed it up. I'm currently training a second model with some tweaked parameters to end up with a smaller model

**Comment by mish15** [comment]
No worries, glad it's helpful. 

In terms of speed, that's a larger model, on par to Google's news one. From memory the current has to scan all vectors, i think @dhowden made the calc about as fast as it's going to go (?), so your best bet is likely to:

a) make sure you're not collecting junk terms. Use a threshold for term addition. Also make sure punctuation, casing, IDs, phone numbers, etc are not causing lots of extra terms you don't care about. 
b) reduce the dimensionality if you can and then 
c) possibly shard the model into clusters and only query the clusters with close center points to the input vector.

Usually a) is the issue. b) is a handy compromise, c) i've never had to do.

**Comment by barthr** [comment]
Thanks for the fast response @mish15 I did an extra cleaning on the data and will try it out to see if the results are a better. It's pretty time consuming to run the model each time because there are more than 200 millions messages (tweets). Currently I'm only interested in the cluster where location indicators are, I think clustering the model will help me omit the things I'm not interested in. 

Thanks for the help!
